function build_10_charging_sessions(mdl)
%PHASE5_EV_LOADS  Generated EV session profiles, and a shed switch per bay.
%
%  TWO CHANGES, both at the four DC Load blocks.
%
%  1. The From Workspace blocks stop carrying hand-typed matrices
%     ([0 5000; 0.2 5000; 0.25 12.8; 1 12.8]) and start reading
%     mg.evLoad{k}, generated by evLoadProfile.m from the session
%     descriptions in mg.evSessions.  A charging bay is now described the way
%     a charging bay behaves - arrive, charge, taper, unplug - rather than as
%     a resistance someone typed, and changing the scenario means editing a
%     session, not a matrix.
%
%  2. A shed switch goes between each profile and its Variable Resistor:
%
%         R = shed_k ? mg.Rload_open : R_profile(t)
%
%     The loads are Variable Resistors, so shedding needs no plant surgery at
%     all - commanding an open circuit IS disconnecting the bay.  No breaker,
%     no extra state, nothing to go wrong on reconnection.
%
%  Idempotent.

if nargin < 1, mdl = 'microgrid'; end
load_system('simulink');
NL = char(10);

bays = { ['From' NL 'Workspace'],  'DC Load',  'shed1'
         ['From' NL 'Workspace1'], 'DC Load1', 'shed2'
         ['From' NL 'Workspace2'], 'DC Load2', 'shed3'
         ['From' NL 'Workspace3'], 'DC Load3', 'shed4' };

for k = 1:size(bays,1)
    fw   = [mdl '/' bays{k,1}];
    load = [mdl '/' bays{k,2}];
    tag  = bays{k,3};
    sw   = [mdl '/Shed ' bays{k,2}];

    % ---- 1. the profile itself ------------------------------------------
    set_param(fw,'VariableName',sprintf('mg.evLoad{%d}',k));

    % ---- 2. the shed switch ---------------------------------------------
    if getSimulinkBlockHandle(sw) > 0, continue; end

    dstPort = get_param(load,'PortHandles').Inport(1);
    srcPort = get_param(fw,'PortHandles').Outport(1);
    lin = get_param(srcPort,'Line');
    if lin > 0, delete_line(lin); end

    p = get_param(load,'Position');
    x = p(1) - 120;  y = p(2);
    add_block('simulink/Signal Routing/Switch', sw, ...
              'Position',[x y-40 x+30 y+60], ...
              'Criteria','u2 > Threshold','Threshold','0.5');
    add_block('simulink/Sources/Constant',[mdl '/Open ' bays{k,2}], ...
              'Position',[x-110 y-45 x-30 y-25],'Value','mg.Rload_open');
    add_block('simulink/Signal Routing/From',[mdl '/From ' tag], ...
              'Position',[x-110 y+5 x-30 y+25],'GotoTag',tag);

    swp = get_param(sw,'PortHandles');
    add_line(mdl, get_param([mdl '/Open ' bays{k,2}],'PortHandles').Outport(1), ...
                  swp.Inport(1), 'autorouting','on');   % shed  -> open circuit
    add_line(mdl, get_param([mdl '/From ' tag],'PortHandles').Outport(1), ...
                  swp.Inport(2), 'autorouting','on');   % the shed flag
    add_line(mdl, srcPort, swp.Inport(3), 'autorouting','on');  % else the profile
    add_line(mdl, swp.Outport(1), dstPort, 'autorouting','on');
end

fprintf('build_10_charging_sessions: 4 bays on generated session profiles, each with a shed switch\n');
end
